site_name: Jacob Performance&Linux Book
site_description: "Jacob's 系统性能&Linux调优技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '系统基础设施优化':
    - '第一节 代码让CPU执行得更快 — CPU缓存' : 'chap1/1CPU_Cache.md'
    - '第二节 内存池提升内存分配的效率' : 'chap1/2Mem_Pool.md'
    - '第三节 哈希表利用索引管理亿级对象' : 'chap1/3Hash_index.md'
    - '第四节 磁盘高效地传输文件零拷贝：PageCache' : 'chap1/4PageCache.md'
    - '第五节 协程快速地实现高并发服务：Coroutine' : 'chap1/5Coroutine.md'
    - '第六节 据业务场景选择合适的锁' : 'chap1/6Locks.md'
  - '系统层网络优化':
    - '第一节 一对多通讯如何实现' : 'chap2/1broadcast_network.md'
    - '第二节 C10M是如何实现事件驱动' : 'chap2/2C10M.md'
    - '第三节 提升TCP三次握手的性能' : 'chap2/3tcp3shakehand.md'
    - '第四节 提升TCP四次挥手的性能' : 'chap2/4tcpshutdown.md'
    - '第五节 TCP缓冲区兼顾并发数量与传输速度' : 'chap2/5tcpchachepool.md'
    - '第六节 调整TCP拥塞控制的性能' : 'chap2/6tcpcongestion.md'
  - '分布式系统优化':
    - '第一节 通过监控找到性能瓶颈': 'chap3/1Mon_perf.md'
    - '第二节 舍弃一致性去换取性能的CAP理论': 'chap3/2perf_cap.md'
    - '第三节 AKF立方体可扩展性来提高性能': 'chap3/3perf_akf.md'
    - '第四节 NWR算法修改读写模型以提升性能': 'chap3/4perf_nwr.md'
    - '第五节 负载均衡：选择Nginx还是OpenResty': 'chap3/5nginx_openresty.md'
    - '第六节 一致性哈希的均衡负载': 'chap3/6hash_consistent.md'
    - '第七节 过期缓存防止缓存被流量打穿': 'chap3/7cache_expire.md'
    - '第八节 消息队列基于异步消息提升性能': 'chap3/8message_queue.md'
    - '第九节 MapReduce通过集群实现离线计算': 'chap3/9map_reduce.md'
    - '第十节 权衡关系数据库与NoSQL数据库': 'chap3/10DB_choice.md'

repo_url: https://github.com/Chao-Xi/jxperfbook.git
repo_name: "jxperfbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'light green'
    accent: 'light green'
  i18n:
    prev: 'Previous'
    next: 'Next'