site_name: Jacob Performance&Linux Book
site_description: "Jacob's 系统性能&Linux调优技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxperfbook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '系统基础设施优化':
    - '第一节 代码让CPU执行得更快 — CPU缓存' : 'chap1/1CPU_Cache.md'
    - '第二节 内存池提升内存分配的效率' : 'chap1/2Mem_Pool.md'
    - '第三节 哈希表利用索引管理亿级对象' : 'chap1/3Hash_index.md'
    - '第四节 磁盘高效地传输文件零拷贝：PageCache' : 'chap1/4PageCache.md'
    - '第五节 协程快速地实现高并发服务：Coroutine' : 'chap1/5Coroutine.md'
    - '第六节 据业务场景选择合适的锁' : 'chap1/6Locks.md'
  - '系统层网络优化':
    - '第一节 一对多通讯如何实现' : 'chap2/1broadcast_network.md'
    - '第二节 C10M是如何实现事件驱动' : 'chap2/2C10M.md'
    - '第三节 提升TCP三次握手的性能' : 'chap2/3tcp3shakehand.md'
    - '第四节 提升TCP四次挥手的性能' : 'chap2/4tcpshutdown.md'
    - '第五节 TCP缓冲区兼顾并发数量与传输速度' : 'chap2/5tcpchachepool.md'
    - '第六节 调整TCP拥塞控制的性能' : 'chap2/6tcpcongestion.md'
  - '分布式系统优化':
    - '第一节 通过监控找到性能瓶颈': 'chap3/1Mon_perf.md'
    - '第二节 舍弃一致性去换取性能的CAP理论': 'chap3/2perf_cap.md'
    - '第三节 AKF立方体可扩展性来提高性能': 'chap3/3perf_akf.md'
    - '第四节 NWR算法修改读写模型以提升性能': 'chap3/4perf_nwr.md'
    - '第五节 负载均衡：选择Nginx还是OpenResty': 'chap3/5nginx_openresty.md'
    - '第六节 一致性哈希的均衡负载': 'chap3/6hash_consistent.md'
    - '第七节 过期缓存防止缓存被流量打穿': 'chap3/7cache_expire.md'
    - '第八节 消息队列基于异步消息提升性能': 'chap3/8message_queue.md'
    - '第九节 MapReduce通过集群实现离线计算': 'chap3/9map_reduce.md'
    - '第十节 权衡关系数据库与NoSQL数据库': 'chap3/10DB_choice.md'
  - 'IT运维面试问题总结':
    - '第一节 IT运维面试问题总结- Linux基础' : 'chap4/1Linux.md'
    - '第二节 IT运维面试问题总结-基础服务、磁盘管理、虚拟平台和系统管理' : 'chap4/2Linux_SVC.md'
    - '第三节 IT运维面试问题总结-运维工具、开源应用(Ceph、Docker、Apache、Nginx等)' : 'chap4/3Linux_tools.md'
    - '第四节 IT运维面试问题总结-数据库、监控、网络管理' : 'chap4/4Linux_db_dia.md'
    - '第五节 IT运维面试问题总结-简述Etcd、Kubernetes、Lvs、HAProxy等' : 'chap4/5k8s_OpenShift.md'
    - '第六节 Python面试' : 'chap4/6Py_interview.md'
    - '第七节 prometheus：要点总结及面试': 'chap4/7Pro_interview.md'
    - 'L8 Data Analyst Interview': 'chap4/8Data_ana_interview1.md'
    - '第八节 分析岗笔试/面试知识点': 'chap4/8Data_ana_interview2.md'
    - 'L9 Top 50 Machine Learning Interview Questions & Answers': 'chap4/9Data_ML_interview.md'
    - 'L10 30 Frequently asked Deep Learning Interview': 'chap4/10Deep_learning.md'
    - 'L11 Redis 核心技术考题':  'chap4/11Redis_rev.md'
    - 'L12 ES 期末考试':  'chap4/12ES_rev.md'
    - 'L13 Istio面试': 'chap4/13istio_rev.md'
    - 'L14 SRE本质就是一个懂运维的资深开发': 'chap4/14sre.md'
  - 'Python 面试题与总结':
    - '1、Apple Interview(3Sum)': 'chap5/1Apple_3sum.md'
    - '2、Python Interview': 'chap5/2Python_interview.md'
    - '3、Longest substring': 'chap5/3GS_longest_substr.md'
    - '4、Remove duplicate in Sort List': 'chap5/4GS_remove_sort_list.md'
    - '5、Reverse Sort List': 'chap5/5Sort_list.md'
    - '6、Remove duplicate from dictionary': 'chap5/6RM_dup_dict.md'
    - '7、Find Maxmium number count in list and nth number': 'chap5/7Find_max.md'
    - '8、GS Interview': 'chap5/8gs_interview.md'
    - '9、Find substring inside String': 'chap5/9Substring.md'
    - '10、Reverse String': 'chap5/10reverse_string.md'
    - '11、Count how many zero in N!': 'chap5/11zeroinN.md'
    - '12、Jump Game': 'chap5/12JumpGame.md'
  - 'Linux 面试题与总结':
    - 'L1 1min 内对 Linux 进行性能诊断': 'chap6/1Linux_perf.md'
    - 'L2 当面试官问你load average时，怎么回答？': 'chap6/2Linux_load_avg.md'
    - 'L3 文件系统inode': 'chap6/3Linux_inode.md'
    - 'L4 运维必须掌握的Linux面试题': 'chap6/4Linux_ops_int.md'
    - 'L5 常见网络编程面试题': 'chap6/5Linux_network_int.md'
    - 'L6 Git 实用技巧记录': 'chap6/6Git_principle.md'
    - 'L7 深入浅出负载均衡': 'chap6/7LoadBalancer.md'
    - 'L8 Linux 面试题 合集CDN': 'chap6/8Linux_all.md'
    - 'L9 Linux面试最高频的5个基本问题（CPU+COMMMAND)': 'chap6/9Linux_five.md'
    - 'L10 HAProxy从零开始到掌握': 'chap6/10haproxy_learn.md'
    - 'L12 从 lsof 开始，深入理解 Linux 虚拟文件系统': 'chap6/12Linux_vir_file.md'
    - 'Linux review': 'chap6/linux_rew.md'
  - 'Companies Interview':
    - '1 Microsoft Interview2021': 'chap7/1Ms.md'
    - '2 Microsoft Interview Algorithm 2021': 'chap7/2Ms_al.md'
    - '3 UBS interview': 'chap7/3ubs.md'
    - '4 Morgan Stanly 2021': 'chap7/4MorganS.md'
    - '5 Apple 2021': 'chap7/5apple.md'
    - '6 AWS': 'chap7/6aws.md'
  - 'Shell Int':
    - '1 Shell 分析服务器日志命令': 'chap8/1shell_logs.md'
    - '2 Linux 系统下查找文件命令总结': 'chap8/2linux_locate.md'

repo_url: https://github.com/Chao-Xi/jxperfbook.git
repo_name: "jxperfbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'light green'
    accent: 'light green'
  i18n:
    prev: 'Previous'
    next: 'Next'